using System;
using ComDevice;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace MeasuringDeviceTest
{
    [TestClass]
    public class DeviceTest
    {
        #region TestData
        string dev = @"<?xml version=""1.0"" encoding=""utf-8""?>
    <device_type name = ""c4352m1"" id=""2"" class_id=""1"">
	    <type>2</type>
	    <num>2</num>
	    <name>c4352m1</name>
	    <scls>
		    <item>
			    <scale>ac</scale>
			    <max_val>30</max_val>
			    <canb_urn>true</canb_urn>
			    <arws>
				    <item>
					    <value>-inf</value>
					    <angle>-5</angle>
				    </item>
				    <item>
					    <value>0</value>
					    <angle>0</angle>
				    </item>
				    <item>
					    <value>1</value>
					    <angle>3.2</angle>
				    </item>
				    <item>
					    <value>2</value>
					    <angle>6.4</angle>
				    </item>
				    <item>
					    <value>3</value>
					    <angle>9.6</angle>
				    </item>
				    <item>
					    <value>4</value>
					    <angle>12.9</angle>
				    </item>
				    <item>
					    <value>5</value>
					    <angle>16.3</angle>
				    </item>
				    <item>
					    <value>6</value>
					    <angle>19</angle>
				    </item>
				    <item>
					    <value>7</value>
					    <angle>22</angle>
				    </item>
				    <item>
					    <value>8</value>
					    <angle>24.8</angle>
				    </item>
				    <item>
					    <value>9</value>
					    <angle>27.6</angle>
				    </item>
				    <item>
					    <value>10</value>
					    <angle>30.3</angle>
				    </item>
				    <item>
					    <value>11</value>
					    <angle>33.1</angle>
				    </item>
				    <item>
					    <value>12</value>
					    <angle>36</angle>
				    </item>
				    <item>
					    <value>13</value>
					    <angle>39</angle>
				    </item>
				    <item>
					    <value>14</value>
					    <angle>41.8</angle>
				    </item>
				    <item>
					    <value>15</value>
					    <angle>44.6</angle>
				    </item>
				    <item>
					    <value>16</value>
					    <angle>47.4</angle>
				    </item>
				    <item>
					    <value>17</value>
					    <angle>50.2</angle>
				    </item>
				    <item>
					    <value>18</value>
					    <angle>53.1</angle>
				    </item>
				    <item>
					    <value>19</value>
					    <angle>56</angle>
				    </item>
				    <item>
					    <value>20</value>
					    <angle>58.8</angle>
				    </item>
				    <item>
					    <value>21</value>
					    <angle>61.8</angle>
				    </item>
				    <item>
					    <value>22</value>
					    <angle>64.5</angle>
				    </item>
				    <item>
					    <value>23</value>
					    <angle>67.6</angle>
				    </item>
				    <item>
					    <value>24</value>
					    <angle>70.4</angle>
				    </item>
				    <item>
					    <value>25</value>
					    <angle>73</angle>
				    </item>
				    <item>
					    <value>26</value>
					    <angle>76.3</angle>
				    </item>
				    <item>
					    <value>27</value>
					    <angle>79.6</angle>
				    </item>
				    <item>
					    <value>28</value>
					    <angle>82.8</angle>
				    </item>
				    <item>
					    <value>29</value>
					    <angle>86.1</angle>
				    </item>
				    <item>
					    <value>30</value>
					    <angle>89.3</angle>
				    </item>
				    <item>
					    <value>+inf</value>
					    <angle>96.5</angle>
				    </item>
			    </arws>
		    </item>
		    <item>
			    <scale>dc</scale>
			    <max_val>30</max_val>
			    <canb_urn>true</canb_urn>
			    <arws>
				    <item>
					    <value>-inf</value>
					    <angle>-5</angle>
				    </item>
				    <item>
					    <value>0</value>
					    <angle>0</angle>
				    </item>
				    <item>
					    <value>1</value>
					    <angle>3.2</angle>
				    </item>
				    <item>
					    <value>2</value>
					    <angle>6.4</angle>
				    </item>
				    <item>
					    <value>3</value>
					    <angle>9.6</angle>
				    </item>
				    <item>
					    <value>4</value>
					    <angle>12.9</angle>
				    </item>
				    <item>
					    <value>5</value>
					    <angle>16.3</angle>
				    </item>
				    <item>
					    <value>6</value>
					    <angle>19</angle>
				    </item>
				    <item>
					    <value>7</value>
					    <angle>22</angle>
				    </item>
				    <item>
					    <value>8</value>
					    <angle>24.8</angle>
				    </item>
				    <item>
					    <value>9</value>
					    <angle>27.6</angle>
				    </item>
				    <item>
					    <value>10</value>
					    <angle>30.3</angle>
				    </item>
				    <item>
					    <value>11</value>
					    <angle>33.1</angle>
				    </item>
				    <item>
					    <value>12</value>
					    <angle>36</angle>
				    </item>
				    <item>
					    <value>13</value>
					    <angle>39</angle>
				    </item>
				    <item>
					    <value>14</value>
					    <angle>41.8</angle>
				    </item>
				    <item>
					    <value>15</value>
					    <angle>44.6</angle>
				    </item>
				    <item>
					    <value>16</value>
					    <angle>47.4</angle>
				    </item>
				    <item>
					    <value>17</value>
					    <angle>50.2</angle>
				    </item>
				    <item>
					    <value>18</value>
					    <angle>53.1</angle>
				    </item>
				    <item>
					    <value>19</value>
					    <angle>56</angle>
				    </item>
				    <item>
					    <value>20</value>
					    <angle>58.8</angle>
				    </item>
				    <item>
					    <value>21</value>
					    <angle>61.8</angle>
				    </item>
				    <item>
					    <value>22</value>
					    <angle>64.5</angle>
				    </item>
				    <item>
					    <value>23</value>
					    <angle>67.6</angle>
				    </item>
				    <item>
					    <value>24</value>
					    <angle>70.4</angle>
				    </item>
				    <item>
					    <value>25</value>
					    <angle>73</angle>
				    </item>
				    <item>
					    <value>26</value>
					    <angle>76.3</angle>
				    </item>
				    <item>
					    <value>27</value>
					    <angle>79.6</angle>
				    </item>
				    <item>
					    <value>28</value>
					    <angle>82.8</angle>
				    </item>
				    <item>
					    <value>29</value>
					    <angle>86.1</angle>
				    </item>
				    <item>
					    <value>30</value>
					    <angle>89.3</angle>
				    </item>
				    <item>
					    <value>+inf</value>
					    <angle>96.5</angle>
				    </item>
			    </arws>
		    </item>
		    <item>
			    <scale>ohm</scale>
			    <max_val>5</max_val>
			    <canb_urn>false</canb_urn>
			    <arws>
				    <item>
					    <value>-inf</value>
					    <angle>96.5</angle>
				    </item>
				    <item>
					    <value>0</value>
					    <angle>89.2</angle>
				    </item>
				    <item>
					    <value>0.01</value>
					    <angle>85.5</angle>
				    </item>
				    <item>
					    <value>0.02</value>
					    <angle>81.9</angle>
				    </item>
				    <item>
					    <value>0.03</value>
					    <angle>78.2</angle>
				    </item>
				    <item>
					    <value>0.04</value>
					    <angle>74.7</angle>
				    </item>
				    <item>
					    <value>0.05</value>
					    <angle>71.7</angle>
				    </item>
				    <item>
					    <value>0.06</value>
					    <angle>69</angle>
				    </item>
				    <item>
					    <value>0.07</value>
					    <angle>66.4</angle>
				    </item>
				    <item>
					    <value>0.08</value>
					    <angle>64.1</angle>
				    </item>
				    <item>
					    <value>0.09</value>
					    <angle>61.8</angle>
				    </item>
				    <item>
					    <value>0.1</value>
					    <angle>59.5</angle>
				    </item>
				    <item>
					    <value>0.12</value>
					    <angle>56.3</angle>
				    </item>
				    <item>
					    <value>0.14</value>
					    <angle>52.8</angle>
				    </item>
				    <item>
					    <value>0.16</value>
					    <angle>50.1</angle>
				    </item>
				    <item>
					    <value>0.18</value>
					    <angle>47.2</angle>
				    </item>
				    <item>
					    <value>0.2</value>
					    <angle>44.8</angle>
				    </item>
				    <item>
					    <value>0.25</value>
					    <angle>40.8</angle>
				    </item>
				    <item>
					    <value>0.3</value>
					    <angle>37.6</angle>
				    </item>
				    <item>
					    <value>0.35</value>
					    <angle>34.6</angle>
				    </item>
				    <item>
					    <value>0.4</value>
					    <angle>31.8</angle>
				    </item>
				    <item>
					    <value>0.45</value>
					    <angle>28.8</angle>
				    </item>
				    <item>
					    <value>0.5</value>
					    <angle>25.6</angle>
				    </item>
				    <item>
					    <value>0.6</value>
					    <angle>21.8</angle>
				    </item>
				    <item>
					    <value>0.7</value>
					    <angle>20.1</angle>
				    </item>
				    <item>
					    <value>0.8</value>
					    <angle>18.3</angle>
				    </item>
				    <item>
					    <value>0.9</value>
					    <angle>16.6</angle>
				    </item>
				    <item>
					    <value>1</value>
					    <angle>14.6</angle>
				    </item>
				    <item>
					    <value>2</value>
					    <angle>11.3</angle>
				    </item>
				    <item>
					    <value>3</value>
					    <angle>7.8</angle>
				    </item>
				    <item>
					    <value>5</value>
					    <angle>4</angle>
				    </item>
				    <item>
					    <value>+inf</value>
					    <angle>0</angle>
				    </item>
			    </arws>
		    </item>
	    </scls>
	    <btns>
		    <item>
			    <btn>1</btn>
			    <value>dc</value>
			    <msg>1</msg>
		    </item>
		    <item>
			    <btn>3</btn>
			    <value>ac</value>
			    <msg>3</msg>
		    </item>
		    <item>
			    <btn>2</btn>
			    <value>ohm</value>
			    <msg>2</msg>
		    </item>
		    <item>
			    <btn>0</btn>
			    <value>off</value>
			    <msg>0</msg>
		    </item>
	    </btns>
	    <limits>
		    <item>
			    <group>special</group>
			    <lims>
				    <item>
					    <limit>0</limit>
					    <angle>0</angle>
					    <msg>48</msg>
				    </item>
				    <item>
					    <limit>0.075</limit>
					    <angle>136</angle>
					    <msg>34</msg>
				    </item>
			    </lims>
		    </item>
		    <item>
			    <group>current</group>
			    <lims>
				    <item>
					    <limit>6</limit>
					    <angle>14</angle>
					    <msg>44</msg>
				    </item>
				    <item>
					    <limit>1.5</limit>
					    <angle>28</angle>
					    <msg>43</msg>
				    </item>
				    <item>
					    <limit>0.6</limit>
					    <angle>44</angle>
					    <msg>42</msg>
				    </item>
				    <item>
					    <limit>0.15</limit>
					    <angle>60</angle>
					    <msg>41</msg>
				    </item>
				    <item>
					    <limit>0.006</limit>
					    <angle>74</angle>
					    <msg>35</msg>
				    </item>
				    <item>
					    <limit>0.0015</limit>
					    <angle>90</angle>
					    <msg>36</msg>
				    </item>
				    <item>
					    <limit>0.0006</limit>
					    <angle>104</angle>
					    <msg>37</msg>
				    </item>
				    <item>
					    <limit>0.00015</limit>
					    <angle>120</angle>
					    <msg>38</msg>
				    </item>
			    </lims>
		    </item>
		    <item>
			    <group>ohm</group>
			    <lims>
				    <item>
					    <limit>1000000</limit>
					    <angle>150</angle>
					    <msg>33</msg>
				    </item>
				    <item>
					    <limit>100000</limit>
					    <angle>164</angle>
					    <msg>32</msg>
				    </item>
				    <item>
					    <limit>10000</limit>
					    <angle>180</angle>
					    <msg>31</msg>
				    </item>
				    <item>
					    <limit>1000</limit>
					    <angle>194</angle>
					    <msg>25</msg>
				    </item>
				    <item>
					    <limit>1</limit>
					    <angle>210</angle>
					    <msg>26</msg>
				    </item>
			    </lims>
		    </item>
		    <item>
			    <group>voltage</group>
			    <lims>
				    <item>
					    <limit>0.3</limit>
					    <angle>222</angle>
					    <msg>27</msg>
				    </item>
				    <item>
					    <limit>1.5</limit>
					    <angle>238</angle>
					    <msg>28</msg>
				    </item>
				    <item>
					    <limit>6</limit>
					    <angle>254</angle>
					    <msg>24</msg>
				    </item>
				    <item>
					    <limit>15</limit>
					    <angle>270</angle>
					    <msg>23</msg>
				    </item>
				    <item>
					    <limit>30</limit>
					    <angle>284</angle>
					    <msg>22</msg>
				    </item>
				    <item>
					    <limit>60</limit>
					    <angle>300</angle>
					    <msg>21</msg>
				    </item>
				    <item>
					    <limit>150</limit>
					    <angle>316</angle>
					    <msg>16</msg>
				    </item>
				    <item>
					    <limit>300</limit>
					    <angle>330</angle>
					    <msg>17</msg>
				    </item>
				    <item>
					    <limit>600</limit>
					    <angle>344</angle>
					    <msg>18</msg>
				    </item>
			    </lims>
		    </item>
	    </limits>
    </device_type>
        ";
        string conf = @"<?xml version=""1.0"" encoding=""utf-8""?>
<device_type name = ""Прибор 2"" id=""2"" type=""2"" serial=""28FFBC6BA1160506"">
  <type>1</type>
  <serial>28FFBC6BA1160506</serial>
  <name>Прибор 2</name>
  <descr>Описание 2</descr>
  <scls>
    <item>
      <scale>dc</scale>
      <arws>
        <item>
          <value>-inf</value>
          <hw_angle>-10</hw_angle>
        </item>
        <item>
          <value>0</value>
          <hw_angle>0</hw_angle>
        </item>
        <item>
          <value>1</value>
          <hw_angle>4</hw_angle>
        </item>
        <item>
          <value>2</value>
          <hw_angle>10</hw_angle>
        </item>
        <item>
          <value>3</value>
          <hw_angle>16</hw_angle>
        </item>
        <item>
          <value>4</value>
          <hw_angle>21</hw_angle>
        </item>
        <item>
          <value>5</value>
          <hw_angle>27</hw_angle>
        </item>
        <item>
          <value>6</value>
          <hw_angle>33</hw_angle>
        </item>
        <item>
          <value>7</value>
          <hw_angle>38</hw_angle>
        </item>
        <item>
          <value>8</value>
          <hw_angle>44</hw_angle>
        </item>
        <item>
          <value>9</value>
          <hw_angle>51</hw_angle>
        </item>
        <item>
          <value>10</value>
          <hw_angle>56</hw_angle>
        </item>
        <item>
          <value>11</value>
          <hw_angle>62</hw_angle>
        </item>
        <item>
          <value>12</value>
          <hw_angle>69</hw_angle>
        </item>
        <item>
          <value>13</value>
          <hw_angle>74</hw_angle>
        </item>
        <item>
          <value>14</value>
          <hw_angle>80</hw_angle>
        </item>
        <item>
          <value>15</value>
          <hw_angle>87</hw_angle>
        </item>
        <item>
          <value>16</value>
          <hw_angle>92</hw_angle>
        </item>
        <item>
          <value>17</value>
          <hw_angle>98</hw_angle>
        </item>
        <item>
          <value>18</value>
          <hw_angle>104</hw_angle>
        </item>
        <item>
          <value>19</value>
          <hw_angle>110</hw_angle>
        </item>
        <item>
          <value>20</value>
          <hw_angle>116</hw_angle>
        </item>
        <item>
          <value>21</value>
          <hw_angle>122</hw_angle>
        </item>
        <item>
          <value>22</value>
          <hw_angle>129</hw_angle>
        </item>
        <item>
          <value>23</value>
          <hw_angle>135</hw_angle>
        </item>
        <item>
          <value>24</value>
          <hw_angle>141</hw_angle>
        </item>
        <item>
          <value>25</value>
          <hw_angle>146</hw_angle>
        </item>
        <item>
          <value>26</value>
          <hw_angle>152</hw_angle>
        </item>
        <item>
          <value>27</value>
          <hw_angle>158</hw_angle>
        </item>
        <item>
          <value>28</value>
          <hw_angle>164</hw_angle>
        </item>
        <item>
          <value>29</value>
          <hw_angle>170</hw_angle>
        </item>
        <item>
          <value>30</value>
          <hw_angle>175</hw_angle>
        </item>
        <item>
          <value>+inf</value>
          <hw_angle>190</hw_angle>
        </item>
      </arws>
    </item>
    <item>
      <scale>ac</scale>
      <arws>
        <item>
          <value>-inf</value>
          <hw_angle>-10</hw_angle>
        </item>
        <item>
          <value>0</value>
          <hw_angle>0</hw_angle>
        </item>
        <item>
          <value>1</value>
          <hw_angle>4</hw_angle>
        </item>
        <item>
          <value>2</value>
          <hw_angle>10</hw_angle>
        </item>
        <item>
          <value>3</value>
          <hw_angle>16</hw_angle>
        </item>
        <item>
          <value>4</value>
          <hw_angle>21</hw_angle>
        </item>
        <item>
          <value>5</value>
          <hw_angle>27</hw_angle>
        </item>
        <item>
          <value>6</value>
          <hw_angle>33</hw_angle>
        </item>
        <item>
          <value>7</value>
          <hw_angle>38</hw_angle>
        </item>
        <item>
          <value>8</value>
          <hw_angle>44</hw_angle>
        </item>
        <item>
          <value>9</value>
          <hw_angle>51</hw_angle>
        </item>
        <item>
          <value>10</value>
          <hw_angle>56</hw_angle>
        </item>
        <item>
          <value>11</value>
          <hw_angle>62</hw_angle>
        </item>
        <item>
          <value>12</value>
          <hw_angle>69</hw_angle>
        </item>
        <item>
          <value>13</value>
          <hw_angle>74</hw_angle>
        </item>
        <item>
          <value>14</value>
          <hw_angle>80</hw_angle>
        </item>
        <item>
          <value>15</value>
          <hw_angle>87</hw_angle>
        </item>
        <item>
          <value>16</value>
          <hw_angle>92</hw_angle>
        </item>
        <item>
          <value>17</value>
          <hw_angle>98</hw_angle>
        </item>
        <item>
          <value>18</value>
          <hw_angle>104</hw_angle>
        </item>
        <item>
          <value>19</value>
          <hw_angle>110</hw_angle>
        </item>
        <item>
          <value>20</value>
          <hw_angle>116</hw_angle>
        </item>
        <item>
          <value>21</value>
          <hw_angle>122</hw_angle>
        </item>
        <item>
          <value>22</value>
          <hw_angle>129</hw_angle>
        </item>
        <item>
          <value>23</value>
          <hw_angle>135</hw_angle>
        </item>
        <item>
          <value>24</value>
          <hw_angle>141</hw_angle>
        </item>
        <item>
          <value>25</value>
          <hw_angle>146</hw_angle>
        </item>
        <item>
          <value>26</value>
          <hw_angle>152</hw_angle>
        </item>
        <item>
          <value>27</value>
          <hw_angle>158</hw_angle>
        </item>
        <item>
          <value>28</value>
          <hw_angle>164</hw_angle>
        </item>
        <item>
          <value>29</value>
          <hw_angle>170</hw_angle>
        </item>
        <item>
          <value>30</value>
          <hw_angle>175</hw_angle>
        </item>
        <item>
          <value>+inf</value>
          <hw_angle>190</hw_angle>
        </item>
      </arws>
    </item>
    <item>
      <scale>ohm</scale>
      <arws>
        <item>
          <value>-inf</value>
          <hw_angle>190</hw_angle>
        </item>
        <item>
          <value>0</value>
          <hw_angle>175</hw_angle>
        </item>
        <item>
          <value>0.01</value>
          <hw_angle>169</hw_angle>
        </item>
        <item>
          <value>0.02</value>
          <hw_angle>162</hw_angle>
        </item>
        <item>
          <value>0.03</value>
          <hw_angle>155</hw_angle>
        </item>
        <item>
          <value>0.04</value>
          <hw_angle>150</hw_angle>
        </item>
        <item>
          <value>0.05</value>
          <hw_angle>144</hw_angle>
        </item>
        <item>
          <value>0.06</value>
          <hw_angle>139</hw_angle>
        </item>
        <item>
          <value>0.07</value>
          <hw_angle>133</hw_angle>
        </item>
        <item>
          <value>0.08</value>
          <hw_angle>129</hw_angle>
        </item>
        <item>
          <value>0.09</value>
          <hw_angle>125</hw_angle>
        </item>
        <item>
          <value>0.1</value>
          <hw_angle>122</hw_angle>
        </item>
        <item>
          <value>0.12</value>
          <hw_angle>115</hw_angle>
        </item>
        <item>
          <value>0.14</value>
          <hw_angle>108</hw_angle>
        </item>
        <item>
          <value>0.16</value>
          <hw_angle>102</hw_angle>
        </item>
        <item>
          <value>0.18</value>
          <hw_angle>98</hw_angle>
        </item>
        <item>
          <value>0.2</value>
          <hw_angle>92</hw_angle>
        </item>
        <item>
          <value>0.25</value>
          <hw_angle>83</hw_angle>
        </item>
        <item>
          <value>0.3</value>
          <hw_angle>75</hw_angle>
        </item>
        <item>
          <value>0.35</value>
          <hw_angle>68</hw_angle>
        </item>
        <item>
          <value>0.4</value>
          <hw_angle>62</hw_angle>
        </item>
        <item>
          <value>0.45</value>
          <hw_angle>57</hw_angle>
        </item>
        <item>
          <value>0.5</value>
          <hw_angle>53</hw_angle>
        </item>
        <item>
          <value>0.6</value>
          <hw_angle>46</hw_angle>
        </item>
        <item>
          <value>0.7</value>
          <hw_angle>41</hw_angle>
        </item>
        <item>
          <value>0.8</value>
          <hw_angle>36</hw_angle>
        </item>
        <item>
          <value>0.9</value>
          <hw_angle>33</hw_angle>
        </item>
        <item>
          <value>1</value>
          <hw_angle>30</hw_angle>
        </item>
        <item>
          <value>2</value>
          <hw_angle>16</hw_angle>
        </item>
        <item>
          <value>3</value>
          <hw_angle>10</hw_angle>
        </item>
        <item>
          <value>5</value>
          <hw_angle>6</hw_angle>
        </item>
        <item>
          <value>+inf</value>
          <hw_angle>0</hw_angle>
        </item>
      </arws>
    </item>
  </scls>
</device_type>
        ";
        #endregion

        [TestMethod]
        public void DeviceCreation()
        {
            //DeviceLogic device = new DeviceLogic(dev, conf);
        }
    }
}
